"""Init migration

Revision ID: 545b0fb75031
Revises: 
Create Date: 2021-01-26 15:34:44.634549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import insert
from backend.models import Question, Category

# revision identifiers, used by Alembic.
revision = '545b0fb75031'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'questions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('question', sa.String(), nullable=True),
        sa.Column('answer', sa.String(), nullable=True),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.Column('difficulty', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # add default data
    default_categories = [
        ('science', 1),
        ('art', 2),
        ('geography', 3),
        ('history', 4),
        ('entertainment', 5),
        ('sports', 6)
    ]
    for (cat_type, cat_id) in default_categories:
        op.execute(insert(Category).values((cat_id, cat_type)))

    default_questions = [
        {
            'question': "Whose autobiography is entitled 'I Know Why the Caged Bird Sings'?",
            'answer': "Maya Angelou",
            'difficulty': 2,
            'category_id': 4,
        },
        {
            'question': "What boxer's original name is Cassius Clay?",
            'answer': "Muhammad Ali",
            'difficulty': 1,
            'category_id': 4,
        },
        {
            'question': "What movie earned Tom Hanks his third straight Oscar nomination, in 1996?",
            'answer': "Apollo 13",
            'difficulty': 4,
            'category_id': 5,
        },
        {
            'question': "What actor did author Anne Rice first denounce, "
                        "then praise in the role of her beloved Lestat?",
            'answer': "Tom Cruise",
            'difficulty': 4,
            'category_id': 5,
        },
        {
            'question': "What was the title of the 1990 fantasy directed by Tim Burton about a young man with "
                        "multi-bladed appendages?",
            'answer': "Edward Scissorhands",
            'difficulty': 3,
            'category_id': 5,
        },
        {
            'question': "Which is the only team to play in every soccer World Cup tournament?",
            'answer': "Brazil",
            'difficulty': 3,
            'category_id': 6,
        },
        {
            'question': "Which country won the first ever soccer World Cup in 1930?",
            'answer': "Uruguay",
            'difficulty': 4,
            'category_id': 6,
        },
        {
            'question': "Who invented Peanut Butter?",
            'answer': "George Washington Carver",
            'difficulty': 2,
            'category_id': 4,
        },
        {
            'question': "What is the largest lake in Africa?",
            'answer': "Lake Victoria",
            'difficulty': 2,
            'category_id': 3,
        },
        {
            'question': "In which royal palace would you find the Hall of Mirrors?",
            'answer': "The Palace of Versailles",
            'difficulty': 3,
            'category_id': 3,
        },
        {
            'question': "The Taj Mahal is located in which Indian city?",
            'answer': "Agra",
            'difficulty': 2,
            'category_id': 3,
        },
        {
            'question': "Which Dutch graphic artist–initials M C was a creator of optical illusions?",
            'answer': "Escher",
            'difficulty': 1,
            'category_id': 2,
        },
        {
            'question': "La Giaconda is better known as what?",
            'answer': "Mona Lisa",
            'difficulty': 3,
            'category_id': 2,
        },
        {
            'question': "How many paintings did Van Gogh sell in his lifetime?",
            'answer': "One",
            'difficulty': 4,
            'category_id': 2,
        },
        {
            'question': "Which American artist was a pioneer of Abstract Expressionism, and a leading exponent of "
                        "action painting?",
            'answer': "Jackson Pollock",
            'difficulty': 2,
            'category_id': 2,
        },
        {
            'question': "What is the heaviest organ in the human body?",
            'answer': "The Liver",
            'difficulty': 4,
            'category_id': 1,
        },
        {
            'question': "Who discovered penicillin?",
            'answer': "Alexander Fleming",
            'difficulty': 3,
            'category_id': 1,
        },
        {
            'question': "Hematology is a branch of medicine involving the study of what?",
            'answer': "Blood",
            'difficulty': 4,
            'category_id': 1,
        },
        {
            'question': "Which dung beetle was worshipped by the ancient Egyptians",
            'answer': "Scarab",
            'difficulty': 4,
            'category_id': 4,
        },
    ]
    for q in default_questions:
        op.execute(insert(Question).values(q))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('categories')
    # ### end Alembic commands ###
